package:
  name: robustraster
  version: "0.4.4"

source:
  path: .

build:
  noarch: python
  number: 1
  script: python -m pip install ./src

requirements:
  build:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - numpy >=2.0
    - xee =0.0.13
    - rioxarray =0.15.0
    - dask =2024.8.1
    - distributed =2024.8.1
    - bokeh <3.9.0
    - cloudpickle =3.0.0
    - lz4 =4.3.3
    - msgpack-python =1.0.8
    - pandas =2.3.3 
    - tornado =6.4.2
    - geopandas =1.0.1
    - gcsfs =2025.3.2
    - gdal =3.10.2
    - rpy2
    - ipykernel =6.29.5
    - geemap =0.36.1
    - docker-py =7.1.0
    - pyarrow =21.0.0
    - fastparquet =2025.12.0  
    - rpy2 =3.6.4
    - python-graphviz
    - scikit-learn =1.7.2

test:
  source_files:
    - tests/
  requires:
    - pytest
    - gdal
  commands:
    - pytest tests/

extra:
  recipe-maintainers:
    - adrianom

about:
  summary: "Test build 0.4.3"
  license: "MIT"
  description: |
    Version 0.4.3